-- Run in Supabase SQL editor.

CREATE TABLE IF NOT EXISTS boxes (
    box_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    resident_name VARCHAR(120) NOT NULL,
    address VARCHAR(255) NOT NULL,
    contact_number VARCHAR(30) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS alerts (
    alert_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    box_id BIGINT NOT NULL,
    detected_language VARCHAR(40) NOT NULL,
    transcript TEXT NOT NULL,
    english_translation TEXT NOT NULL,
    severity VARCHAR(20) NOT NULL CHECK (severity IN ('URGENT', 'UNCERTAIN', 'NON-URGENT')),
    confidence_score FLOAT NOT NULL CHECK (confidence_score >= 0 AND confidence_score <= 1),
    keywords TEXT[] DEFAULT '{}',
    distress_indacators TEXT[] DEFAULT '{}',
    status VARCHAR(20) NOT NULL DEFAULT 'open' CHECK (status IN ('open', 'acknowledged')),
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    acknowledged_at TIMESTAMPTZ NULL,
    CONSTRAINT fk_alerts_boxes FOREIGN KEY (box_id) REFERENCES boxes (box_id)
);

CREATE INDEX IF NOT EXISTS idx_alerts_created_at ON alerts (created_at DESC);
CREATE INDEX IF NOT EXISTS idx_alerts_status ON alerts (status);